# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bef924debfadc8d321826e9b8e11e8b7c0f7e008476ca7c0cba93921d08ff0a7832cfcb7ff876c494c951d65fb6a66f7e4742b8de4bde5e3fa18a50a627a76a

test:
  secret_key_base: 91e4065af4b2295d22ff16e40a5e98c8c2e0cfa21f2bc5b4185b038614346191f85aa8d1207a5eda916b3cbb442b564b4b99c10ea6d2d4330dc4d176f341b2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
